apiVersion: v2
name: ontu-schedule-bot
description: ONTU Schedule Bot - Client service that communicates with admin backend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ontu-schedule
  - bot
  - client
maintainers:
  - name: ONTU Schedule Team
