{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sealed-secrets.serviceAccountName" . }}
  labels:
    {{- include "sealed-secrets.labels" . | nindent 4 }}
{{- end }}
