---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontu-schedule-bot-admin
spec:
  template:
    spec:
      containers:
      - name: ontu-schedule-bot-admin
        image: ghcr.io/wandering-cursor/ontu-schedule-bot-admin:1.1.1-b10
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      containers:
        - name: ontu-schedule-bot-admin
          image: ghcr.io/wandering-cursor/ontu-schedule-bot-admin:1.1.1-b10
---
apiVersion: batch/v1
kind: Job
metadata:
  name: collect-static
spec:
  template:
    spec:
      containers:
        - name: ontu-schedule-bot-admin
          image: ghcr.io/wandering-cursor/ontu-schedule-bot-admin:1.1.1-b10
