apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: grafana/promtail:3
        imagePullPolicy: Always
        args: ["-config.file=/etc/promtail/promtail.yaml"]
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: true
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: positions
          mountPath: /run/promtail
        - name: varlog
          mountPath: /var/log
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: containers
          mountPath: /var/log/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: positions
        emptyDir: {}
      - name: varlog
        hostPath:
          path: /var/log
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: containers
        hostPath:
          path: /var/log/containers
