# Secret containing PostgreSQL credentials
# NOTE: In production, replace this with a SealedSecret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  database: {{ .Values.auth.database | quote }}
  # Connection string for applications
  connection-string: {{ include "postgresql.connectionString" . | quote }}
