# StatefulSet for Dragonfly
# Uses StatefulSet to ensure stable network identity and persistent storage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dragonfly.fullname" . }}
  labels:
    {{- include "dragonfly.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dragonfly.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "dragonfly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dragonfly.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: dragonfly
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dragonfly
              containerPort: 6379
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          args:
            # Directory for snapshots
            - --dir=/data
            {{- if .Values.auth.password }}
            # Authentication
            - --requirepass=$(DRAGONFLY_PASSWORD)
            {{- end }}
            {{- if gt (int .Values.config.maxMemory) 0 }}
            # Maximum memory
            - --maxmemory={{ .Values.config.maxMemory }}mb
            {{- end }}
            {{- if gt (int .Values.config.threads) 0 }}
            # Number of threads
            - --proactor_threads={{ .Values.config.threads }}
            {{- end }}
            {{- if .Values.config.snapshot }}
            # Enable snapshots
            - --snapshot_cron=0 *{{ div .Values.config.snapshotInterval 3600 }} * * *
            {{- end }}
            {{- if .Values.metrics.enabled }}
            # Metrics port
            - --metrics_port={{ .Values.metrics.port }}
            {{- end }}
          env:
            {{- if .Values.auth.password }}
            - name: DRAGONFLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dragonfly.fullname" . }}
                  key: password
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: dragonfly
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - dragonfly --logtostderr=1 --alsologtostderr=0 -v=0 --port 0 --admin_port 0
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "dragonfly.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
