apiVersion: v2
name: example-nginx
description: Example NGINX application demonstrating secrets and environment variables usage
type: application
version: 1.0.0
appVersion: "1.25"
keywords:
  - nginx
  - example
  - demo
maintainers:
  - name: ONTU Schedule Team
