apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ontu-schedule
  
  source:
    repoURL: https://github.com/Wandering-Cursor/ontu-schedule-gitops.git
    targetRevision: HEAD
    path: infrastructure/sealed-secrets
    helm:
      releaseName: sealed-secrets
  
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
