{{- if .Values.podDisruptionBudget.enabled }}
# PodDisruptionBudget for ONTU Schedule Bot Admin
# Ensures minimum number of pods are available during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ontu-schedule-bot-admin.fullname" . }}
  labels:
    {{- include "ontu-schedule-bot-admin.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ontu-schedule-bot-admin.selectorLabels" . | nindent 6 }}
{{- end }}
