{{- if not .Values.database.useExternalSecret }}
# Secret for ONTU Schedule Bot Admin
# NOTE: In production, replace this with a SealedSecret
# This is only used if not using external secrets from infrastructure components
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontu-schedule-bot-admin.fullname" . }}
  labels:
    {{- include "ontu-schedule-bot-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database password (only if not using external secret)
  database-password: "changeme"
{{- end }}
