apiVersion: v2
name: postgresql
description: A Helm chart for deploying PostgreSQL database
type: application
version: 0.1.0
appVersion: "18.1.0"

dependencies:
  - name: postgresql
    version: "18.1.13"
    repository: https://charts.bitnami.com/bitnami
