apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  labels:
    app: loki
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        imagePullPolicy: IfNotPresent
        args: ["-config.file=/etc/loki/loki.yaml"]
        ports:
        - name: http
          containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: loki-data
          mountPath: /var/loki
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          runAsNonRoot: true
      initContainers:
      - name: init-permissions
        image: busybox:1.36
        command: ["sh", "-c", "mkdir -p /var/loki/rules /var/loki/chunks /var/loki/wal /var/loki/compactor && chown -R 10001:10001 /var/loki"]
        volumeMounts:
        - name: loki-data
          mountPath: /var/loki
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
  volumeClaimTemplates:
  - metadata:
      name: loki-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
